from core.weex_api import upload_ai_log
import pandas as pd
import numpy as np

MODEL = "NovaX-GA-v3 (Genetic AI Strategy Engine)"


# -------------------------------------------------
# Helpers
# -------------------------------------------------

def _safe(obj):
    """
    Recursively convert objects to JSON-safe types
    """
    if isinstance(obj, dict):
        return {k: _safe(v) for k, v in obj.items()}
    if isinstance(obj, pd.DataFrame):
        return obj.to_dict(orient="records")
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (int, float, str, bool)) or obj is None:
        return obj
    return str(obj)


def _build_explanation(decision, score, meta):
    """
    Build a WEEX-compliant natural language explanation (<=1000 chars)
    """
    parts = [
        "AI decision generated by a genetic strategy engine",
        f"Decision={decision}",
        f"Score={round(score, 4) if score is not None else 'N/A'}"
    ]

    if isinstance(meta, dict):
        reason = meta.get("reason")
        if reason:
            parts.append(f"AI Reasoning={reason}")

    return " | ".join(parts)[:1000]


# -------------------------------------------------
# Main logger
# -------------------------------------------------

def push_ai_log(
    stage,
    genome,
    X,
    btc,
    micro,
    score,
    decision,
    order_id=None,
    meta=None
):
    """
    Upload AI log to WEEX in strict compliance with:
    POST /capi/v2/order/uploadAiLog
    """

    # ---------- Genome safety ----------
    if genome is None:
        genome_payload = {}
        entry_threshold = None
    elif hasattr(genome, "__dict__"):
        genome_payload = genome.__dict__
        entry_threshold = getattr(genome, "entry", None)
    elif isinstance(genome, dict):
        genome_payload = genome
        entry_threshold = genome.get("entry")
    else:
        genome_payload = {}
        entry_threshold = None

    # ---------- INPUT (required by WEEX) ----------
    input_data = {
        "strategy": {
            "type": "genetic_algorithm",
            "genome_id": genome_payload.get("id"),
            "entry_threshold": entry_threshold
        },
        "features": {
            "score": round(score, 6) if score is not None else None,
            "window_size": len(X) if hasattr(X, "__len__") else None
        }
    }

    # ---------- OUTPUT (required by WEEX) ----------
    output_data = {
        "decision": decision,
        "score": round(score, 6) if score is not None else None
    }

    if meta:
        output_data["meta"] = _safe(meta)

    # ---------- Explanation ----------
    explanation = _build_explanation(decision, score, meta)

    # ---------- Upload (DIRECT → weex_api) ----------
    return upload_ai_log(
        order_id=order_id,
        stage=stage,
        model=MODEL,
        input_data=_safe(input_data),
        output_data=_safe(output_data),
        explanation=explanation
    )
